language: objective-c

before_install:
  - gem install cocoapods
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
  - xctool -workspace O365-iOS-Snippets.xcworkspace -scheme O365-iOS-Snippets -sdk iphonesimulator
